# Generated by Django 6.0.2 on 2026-02-22 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_address', models.TextField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_time', models.TimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('is_tax_deductible', models.BooleanField(default=False)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('raw_ocr_text', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'ordering': ['-total_price'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'category'],
                'unique_together': {('user', 'category', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'receipt_date'], name='receipts_re_user_id_169091_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'category'], name='receipts_re_user_id_35ffd7_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'tax_year'], name='receipts_re_user_id_9b3782_idx'),
        ),
    ]
